# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "example-dependency"
        versions: ["1.x"]

# Trigger Dependabot on pull request to main
on:
  pull_request:
    branches:
      - main