name: Dependabot PR

on:
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dependabot
        uses: dependabot/dependabot-core@v1
        with:
          package-manager: "devcontainers"
          directory: "/"